Game-as-a-Service/LoveLetter

- .github/workflows/tests.yml
- .gitignore
- love_letter/web/example_api.py
- poetry.lock
- pyproject.toml
- tests/test_example_apis.py
* `love_letter/web/example_api.py` 增加 fastapi 的常用方法
* `tests/test_example_apis.py` 增加 test http client 的用法
* 在 github action 加入測試的流程
#11
> Add example apis

- .github/workflows/tests.yml
> Run tests for each PR

- love_letter/models/__init__.py
- love_letter/service/__init__.py
- love_letter/web/app.py
- love_letter/web/dto/__init__.py
- tests/test_simple_path_e2e.py
> Rewrite play-card actions

- features/handmaid.feature
- features/steps/common.py
- love_letter/models/cards.py
> add handmaid behave

- love_letter/models/__init__.py
- love_letter/models/cards.py
- love_letter/models/exceptions.py
- love_letter/service/__init__.py
- tests/test_game_rules.py
- tests/test_simple_path_e2e.py
> 實作遊戲未開始至開始的相關規則

- features/king.feature
- features/steps/common.py
- love_letter/models/__init__.py
- love_letter/models/cards.py
> add king behave

- features/king.feature
- features/steps/common.py
變更第 2 組 Example，相關討論在
https://github.com/Game-as-a-Service/LoveLetter/pull/31/files/af878bce6e0cd1ec04a5e8deb7d56279de14891c#r1042451063
> 更新國王的 Example

- features/guard.feature
- features/priest.feature
- features/steps/common.py
- love_letter/models/__init__.py
- love_letter/models/cards.py
- love_letter/service/__init__.py
- love_letter/web/app.py
- tests/test_lose_handmaid_protected.py
> [TDD] 經過一輪後，侍女的保護失效

- tests/test_lose_handmaid_protected.py
- #33 
- 少寫指定第一輪開始玩家，導致開始玩家為亂數XD
> :bug: 修改測試案例漏指定第一輪玩家

- features/prince.feature
- features/steps/common.py
- love_letter/models/__init__.py
add player_draw_card function in common.py
add drop_cards function in class Player
> add_prince_scenario

- love_letter/repository/__init__.py
- love_letter/service/__init__.py
- love_letter/web/app.py
- poetry.lock
- pyproject.toml
- tests/test_game_service.py
- tests/test_simple_path_e2e.py
#45 
* 目前沒有 `帳號註冊` 的概念，只要玩家 `建立遊戲` 或 `加入遊戲`，我們都幫他們建立臨時的 Player 物件。
* 使用 Repository 取代先前的 `fake_database`，開成介面與實作，預留替換成 mongodb 的位置。
> 實作建立遊戲與加入遊戲

- love_letter/models/__init__.py
- love_letter/models/cards.py
- love_letter/service/__init__.py
- love_letter/web/app.py
- love_letter/web/dto/__init__.py
- tests/test_game_service.py
- tests/test_simple_path_e2e.py
#46 
* Player 可以透過 `get_status` 取得遊戲狀態
* `get_status` 是針對每個 Player 個人的資料，因為 Player 只看得到自己的卡片，不知道別人的卡片。
```json
{
"game_id": "a41695c7eece44f48a0b421318892276",
"rounds": [
{
"players": [
{
"name": "player-a",
"out": false,
"cards": [
{
"name": "侍女",
"description": "<description>",
"value": 4
},
{
"name": "王子",
"description": "<description>",
"value": 5
}
]
},
{
"name": "player-b",
"out": false,
"cards": []
}
],
"winner": null,
"turn_player": {
"name": "player-a",
"out": false,
"cards": [
{
"name": "侍女",
"description": "<description>",
"value": 4
},
{
"name": "王子",
"description": "<description>",
"value": 5
}
]
}
}
]
}
```
```json
{
"game_id": "a41695c7eece44f48a0b421318892276",
"rounds": [
{
"players": [
{
"name": "player-a",
"out": false,
"cards": []
},
{
"name": "player-b",
"out": …
```
> 實作 player context

- features/countess.feature
- features/steps/common.py
- 原本
```py
Scenario: 玩家出牌 需出伯爵夫人
Given 玩家A 持有 國王
When 系統發牌給 玩家A 伯爵夫人
Then 玩家A 成功打出 伯爵夫人
Scenario: 玩家出牌 無法出國王
Given 玩家A 持有 國王
When 系統發牌給 玩家A 伯爵夫人
Then 玩家A 無法打出 國王
```
- 修改後
```py
Scenario: 玩家出牌 需出伯爵夫人
Given 玩家A 持有 國王 伯爵夫人
When 玩家A 出牌 伯爵夫人
Then 玩家A 成功打出
Scenario: 玩家出牌 無法出國王
Given 玩家A 持有 國王 伯爵夫人
When 玩家A 出牌 國王
Then 玩家A 無法打出
```
> 修改伯爵夫人Scenario描述

- love_letter/models/__init__.py
- love_letter/models/cards.py
- tests/test_players.py
Currently the logic of comparing scores is incomplete: didn't consider a tie in the hand cards.
This PR fixes this issue and adds unit tests for these cases.
> Improve the logic of comparing the scores of two players.

- features/guard.feature
- features/steps/common.py
- love_letter/models/cards.py
fix bug - guard could not guess guard
#37
> fix bug - guard could not guess guard

- love_letter/models/__init__.py
- #44 
- 主要是把這段改掉
https://github.com/Game-as-a-Service/LoveLetter/blob/8d33850a646d6c912c06333cf5c32adae065e4d4/love_letter/models/__init__.py#L124-L130
> [Refactor] 改card_action寫法

- features/steps/common.py
- love_letter/models/__init__.py
- love_letter/models/cards.py
- love_letter/repository/__init__.py
- love_letter/service/__init__.py
- tests/test_card_behave.py
- tests/test_deck.py
- tests/test_game_rules.py
- tests/test_game_service.py
- tests/test_players.py
- tests/test_simple_path_e2e.py
開專案時，從我的編輯器(VS Code)裡面開專案看到很多typing的警告。
這個PR清理掉大部分的警告，除了少數一些在test裡面的dict。
> Resolve typing warnings.

- love_letter/models/__init__.py
- tests/test_card_behave.py
add test: when there is only one player, then the player is winner and get one token of affection
todo: when deck has no card, need to judge who is the winner
> add test: when there is only one player, then the player is winner and get one token of affection

- .github/workflows/linters.yaml
- .pre-commit-config.yaml
- README.md
- features/steps/common.py
- features/steps/tutorial.py
- love_letter/models/__init__.py
- love_letter/models/cards.py
- love_letter/repository/__init__.py
- love_letter/service/__init__.py
- love_letter/web/app.py
- love_letter/web/dto/__init__.py
- love_letter/web/example_api.py
- poetry.lock
- pyproject.toml
- tests/test_card_behave.py
- tests/test_deck.py
- tests/test_example_apis.py
- tests/test_game_rules.py
- tests/test_game_service.py
- tests/test_simple_path_e2e.py
- 為了解決排版、import 多個package問題，所以引入`black`、`isort`套件
- 引入`pre-commit`的方式，讓我們在commit的時候就會自己幫你觸發上面兩個套件了，觸發完後會自動幫你處理好，再次commit就能正常commit了。(當pre-commit的時候必須要有對應的套件才會正常觸發)
- 相關的設定方式也可以參考這篇: https://hackmd.io/@w0q1KtsNQnGPdy54fx-yWg/BJHnjnoKj
```shell
poetry install
pre-commit install --install-hooks
git commit
```
- pylint套件這個我不打算上，因為目前看起來有很多要修改的地方，有點懶得改，看哪天心血來潮再來加上去。大家可以先裝在自己的local端就好
- https://plugins.jetbrains.com/plugin/11084-pylint
> 增加black、isort套件

- frontend/src/apis/index.tsx
- frontend/src/components/Cards.tsx
- frontend/src/components/CreateOrJoinGame.tsx
- frontend/src/components/Deck.tsx
- frontend/src/components/GameEvents.tsx
- frontend/src/components/GameRoom.tsx
- frontend/src/components/GameStatusBoard.tsx
- frontend/src/components/PlayerHand.tsx
- frontend/src/providers/index.tsx
React projects typically follow a few straightforward conventions:
- Component names are written in PascalCase.
- Other names are written in camelCase.
If you're interested in learning more, Airbnb has provided a comprehensive reference guide on React conventions, which we don't necessarily follow but may be helpful:
**[https://github.com/airbnb/javascript/tree/master/react#naming](https://github.com/airbnb/javascript/tree/master/react#naming)**
> [Chore] fix function naming

- love_letter/models/__init__.py
- love_letter/models/event.py
- love_letter/repository/__init__.py
- love_letter/usecase/create_game.py
- love_letter/usecase/get_status.py
- love_letter/usecase/join_game.py
- love_letter/usecase/play_card.py
- love_letter/usecase/start_game.py
- love_letter/web/app.py
- love_letter/web/presenter.py
- tests/test_game_service.py
https://youtu.be/UEAodcYaNk0
修改上次開會的時候提出的問題，presenter、events的放置位置
怎麼修改？可以參考這個講解
https://youtu.be/DiegoOtQpwY
> [Chore] Rewrite presenter and events
